### ISSUE TITLE
LinePlusBarChart: multiple lines and filters

### ISSUE THREAD

**Issue by pimlinders** [novus/nvd3#640] opened 2014-08-14 15:12 UTC
The filters don't work as expected when 2 lines are added to the LinePLusBarChart. I've put up a jsfiddle to demonstrate the issue

http://jsfiddle.net/4eu8LLqt/

Disabling line 2 results the line changing colors but still visible. Disabling line 1 removes both line 1 and 2 regardless of the current disable state of line 2.

**Comment by liquidpele** [comment] 2015-02-10 13:21
Verified this is still a bug.   When using 2 lines, trying to disable the 2nd line just makes it turn the same color as line 1, and trying to show only the second line shows nothing.

**Comment by liquidpele** [comment] 2015-02-10 14:03
Duplicate of https://github.com/novus/nvd3/issues/463

**Closed by liquidpele** 2015-02-10 14:03 UTC
Labels: Bug
