### ISSUE TITLE
linechart viewfinder rendered without right handle when initialized with brushExtent

### ISSUE THREAD

**Issue by fbuchinger** [novus/nvd3#385] opened 2013-12-16 10:03 UTC
When intializing the linechart with a viewfinder and a fixed `brushExtent` (e.g. `[200, 250]`), the right handle of the viewfinder is only partially rendered. Its rectangle "cover" is missing:

![linechart_viewfinder_fixed_brushextent](https://f.cloud.github.com/assets/287434/1753263/d6a4b2e4-6638-11e3-83e3-49dc1cbabd60.png)

**Comment by NSudhir** [comment] 2015-01-13 19:42
Hi can you send me the code for this chart?

**Comment by liquidpele** [comment] 2015-03-11 05:25
This is a duplicate of this more recent bug (which I added a jsfiddle for that reproduces it)

**Comment by liquidpele** [comment] 2015-03-11 05:26
the other issue: https://github.com/novus/nvd3/issues/855

**Closed by liquidpele** 2015-03-11 05:26 UTC
Labels: duplicate
