### ISSUE TITLE
nv object is not defined. used meteor to add nvd3:nvd3 

### ISSUE THREAD

**Issue by tdmoneybanks** [novus/nvd3#1230] opened 2015-09-02 21:00 UTC
Hi, I am using the official nvd3 package on atmosphere and having a problem accessing the nv object. the only line I have added to my project is ` var chart = nv.models.lineChart();` and getting "cannont call models of undefined" as an error. any ideas? thanks.

**Comment by portante** [comment] 2015-09-03 02:49
@tdmoneybanks, what is the order in which you load your javascript modules?

**Comment by tdmoneybanks** [comment] 2015-09-03 03:24
@portante Meteor's build tool handles compiling the js assets however I can check the head of the doc within dev mode to see. Doing that, I see that d3 is loaded into the DOM before nvd3.

**Comment by maxlibin** [comment] 2015-09-03 09:40
same project for me, after added nvd3:nvd3,
 add:
<link href="nv.d3.min.css" rel="stylesheet">
<script src="nv.d3.min.js"></script> 
to template, get nv undefined.

**Comment by liquidpele** [comment] 2015-09-03 11:57
duplicate of https://github.com/novus/nvd3/issues/1185

**Closed by liquidpele** 2015-09-03 11:57 UTC
