### ISSUE TITLE
TypeError: d.data is undefined for line charts under some specific conditions

### ISSUE THREAD

**Issue by sbromberger** [novus/nvd3#402] opened 2014-01-05 17:58 UTC
I apologize in advance for the inadequacy of this bug report.

With a multi-series linechart in which one or more series share a data point, a TypeError is raised. Setting lines.scatter.useVoronoi(false) eliminates the error.

With data of 

```
var Data = [
  {
    "values": [
      {"x": 0, "y": 1},
      {"x": 6, "y": 2}  // common to Line2
    ],
    "key": "Line1",
    "color": "blue"
  },
  {
    "values": [
      {"x": 0, "y": 8},
      {"x": 6, "y": 2}  // common to Line1
    ],
    "key": "Line2",
    "color": "green"
  }
]
```
and code of 

```
 nv.addGraph(function() {
   var chart = nv.models.lineChart();

   chart.xAxis
       .axisLabel('Time (ms)')
       .tickFormat(d3.format(',r'));

   chart.yAxis
       .axisLabel('Voltage (v)')
       .tickFormat(d3.format('.02f'));

   d3.select('#chart svg')
       .datum(Data)
     .transition().duration(500)
       .call(chart);

   nv.utils.windowResize(function() { d3.select('#chart svg').call(chart) });

   return chart;
 });
```

The line graphs draw fine, but the console logs an error:

TypeError: 'undefined' is not an object (evaluating d.data) in nv.d3.js line 11190

When I add lines.scatter.useVoronoi(false), the error disappears. When I change the data so that the series have no points in common, the error also disappears (independent of the useVoronoi setting).

**Comment by liquidpele** [comment] 2015-03-10 03:42
This appears to be a duplicate of https://github.com/novus/nvd3/issues/521

However, I can't seem to reproduce the issue anymore... here is a jsfiddle attempted to do so:   http://jsfiddle.net/9ExJG/5/

Closing until we can reproduce and because this issue is pretty old.

**Closed by liquidpele** 2015-03-10 03:42 UTC
