### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by ZhekaV** [novus/nvd3#389] opened 2013-12-18 16:19 UTC
On x axis i need to show dates as in 'x_axis' array, thats why i use 
d3.requote data[0]['x_axis'][d],
not d3.time.

And got problem, if array with values less then, lets say 5 (depending on svg sizes), i got error, so i always has to provide array with right size of data.

Can somebody give me advice about it?

![2013-12-18 17 57 19](https://f.cloud.github.com/assets/5268758/1774749/acad806c-67fd-11e3-881b-7274d3bf49e1.png)

    nv.addGraph ->

      chart = nv.models.lineChart()
      chart_container = '#nvd3_chart svg'

      chart.xAxis
        .tickFormat (d) ->
          d3.requote data[0]['x_axis'][d]
      chart.yAxis
        .tickFormat d3.format(',r')

      d3.select(chart_container)
        .datum(data)
        .transition().duration(500)
        .call chart

      nv.utils.windowResize ->
        d3.select(chart_container)
          .call chart

      chart

data:
![2013-12-18 18 07 09](https://f.cloud.github.com/assets/5268758/1774815/88855114-67fe-11e3-8316-7a297b2addce.png)

![2013-12-18 18 13 01](https://f.cloud.github.com/assets/5268758/1774909/d694161e-67ff-11e3-89ac-0ab69786e7d9.png)

**Comment by liquidpele** [comment] 2015-02-12 04:00
This issue is really old, from the example code it looks like rchart maybe?... I haven't seen this error so closing this.  Please reopen if still an issue, and provide reproduction using just nvd3, preferably in something like jsfiddle so we can see it in action.  Thanks!

**Closed by liquidpele** 2015-02-12 04:00 UTC
