### ISSUE TITLE
Problem with margin management

### ISSUE THREAD

**Issue by dthevenin** [novus/nvd3#378] opened 2013-12-10 03:08 UTC
Hello

I'am using a "lineChart" model, and I'm not able to configure properly the margin.top.
* first I have strange margin when I activate or not the legend (please ref the following pictures)
* secondly what ever the legend is activated or not, the margin.top configuration does not work; ex: myChart.margin ({top: 150});

With the Legend, the lineChart (green and red) are upper my other graphs (because the margin.top is automatically configured to 30) 

![screen shot 2013-12-10 at 12 00 22](https://f.cloud.github.com/assets/985508/1711205/46bedc40-6147-11e3-9d17-87c9ab1ab4a3.png)

Without the Legend, the lineChart (green and red) are "correctly"  positioned (the margin.top is automatically configured to 50) 

![screen shot 2013-12-10 at 11 59 47](https://f.cloud.github.com/assets/985508/1711207/56077130-6147-11e3-9dad-2b1a02ee8f7a.png)

I have looked into the code, and you do "margin.top = legend.height();" when a legend is activated.
It means we should not try to configure margin?

Cheers

PS: Tks for your lib it awesome :-)

**Comment by liquidpele** [comment] 2015-03-10 14:09
Looks like a duplicate of https://github.com/novus/nvd3/issues/515 which Robin was working on, closing this one.  Thanks for the report though!

**Closed by liquidpele** 2015-03-10 14:09 UTC

**Comment by robinfhu** [comment] 2015-03-10 14:11
This is a big problem actually, one which I struggle to find a clean solution to.  Margin:top basically does not do anything if showLegend=true.  If showLegend=false, margin:top suddenly works.  

I did attempt a solution in https://github.com/novus/nvd3/pull/833, but I went down a rabbit hole and more margin issues emerged.
