### ISSUE TITLE
Problem with some charts and ShadowDOM

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#877] opened 2015-03-12 19:09 UTC
@liquidpele after your tooltip pull request, the line, cumulativeLine and stackedArea charts started to work perfectly under Shadow DOM (at least with the tooltips).

The problem is, with all other charts, the tooltips just stopped to appear. The code of my project that adds ShadowDOM to nvd3 is here:
https://github.com/RenatoUtsch/polynvd3/tree/development

Two links for examples of the bug:
StackedArea (working perfectly): http://renatoutsch.com.br/bower_components/polynvd3/nvd3-stacked-area-chart/demo.html
Scatter (broken): http://renatoutsch.com.br/bower_components/polynvd3/nvd3-scatter-chart/demo.html

Other examples can be found here (currently only the bullet chart should be broken):
http://renatoutsch.com.br/bower_components/polynvd3/

What did you do differently with the other charts that with those three that are working you didn't? All I know is that they have interactive guideline while the others don't.

**Comment by liquidpele** [comment] 2015-03-12 19:29
So is it working when interactive guideline is enabled, or is it not working on some charts regardless even if they have that option and you enable it?

**Comment by RenatoUtsch** [comment] 2015-03-12 19:37
If I disable interactive guideline the three charts that currently work stop working too.

**Comment by liquidpele** [comment] 2015-03-12 19:52
OK.  Probably an issue due to putting tooltip div on body instead of container.  There is an option to specify container on chart.tooltip object.

**Comment by RenatoUtsch** [comment] 2015-03-13 13:58
Yes, it seems that the tooltip appears in the wrong place when it is on the body.

**Comment by liquidpele** [comment] 2015-03-13 15:27
try specifying chart container to see if that fixes it for shadowdom: 

    chart.tooltip.chartContainer(getElementById('#div_containing_the_svg'));

The interactive guideline does that automatically, but normal tooltips just default to using document.body

**Comment by liquidpele** [comment] 2015-03-14 23:04
Okay, so I took a look at your project and polymer, neat stuff.  It looks like in your abstract-chart model, you just need to enforce the tooltip being in the container of the svg... just glancing at it, it looks like you save the svg object via 

    this.svg = d3.select(this.$.svg);

So you could just do something like this in the createChart function maybe

    if(chart.tooltip) {
        chart.tooltip.chartContainer(this.svg.node().parentNode); 
    }

That should make it create he tooltip dom in the same way that the interactive layer does, which you said was working.

**Comment by RenatoUtsch** [comment] 2015-03-14 23:15
@liquidpele Thanks. Yeah, I save the svg like that.

Ah, okay, I was just doing this:
```javascript
chart.tooltip.chartContainer(this.svg.node().parentNode); 
```

And I was getting an error in one of the charts. I needed to test for chart.tooltip then.

Now the tooltip is working in most of the charts, but the pie chart is still not working.

**Comment by liquidpele** [comment] 2015-03-14 23:38
Hmm, that's weird, the pie chart works the exact same as the bar charts... is there an error in the js console?

**Comment by RenatoUtsch** [comment] 2015-03-15 13:24
chart.tooltip is not defined in the pie chart.

**Comment by liquidpele** [comment] 2015-03-15 13:36
Oh!  Well that's a bug!

**Comment by liquidpele** [comment] 2015-03-15 20:20
Fixed in dev branch.

**Comment by liquidpele** [comment] 2015-03-15 20:21
Let me know if there is anything else not working.

**Comment by RenatoUtsch** [comment] 2015-03-15 22:11
Okay, this fixed it here.

I'll continue tomorrow to test everything.

Thanks!

**Comment by RenatoUtsch** [comment] 2015-03-15 22:30
@liquidpele a warning about nv.utils.optionsFunc being deprecated appears in all charts. The problem is, I don't use it. Maybe some code is still calling this function?

**Comment by liquidpele** [comment] 2015-03-15 23:01
Well... I have no intention of deprecating that anyway, I guess I should remove it.

**Comment by liquidpele** [comment] 2015-03-16 23:31
everything working?

**Comment by RenatoUtsch** [comment] 2015-03-17 01:13
Dunno if it is a problem with bower, but nvd3#development still warns about nv.utils.optionsFunc being deprecated.

**Comment by liquidpele** [comment] 2015-03-17 01:17
Oh yea, I forgot.   Okay, I just removed that.  Any other issues related to shadow-dom?

**Comment by RenatoUtsch** [comment] 2015-03-17 01:20
There are still some issues I was trying to solve:
- All charts with interactive guideline are not showing the hover circles when under a point in the chart. The scatter chart also.
- I'm having a problem with the pie chart: when hovering on the chart areas, the pie chart actually gets smaller (2nd example of the pie demo, the first with NAN is probably my fault)
- The stacked area chart is having problems to renderize on some conditions... don't yet know which ones, need to search more.

**Comment by liquidpele** [comment] 2015-03-17 01:25
The pie chart thing sounds like https://github.com/novus/nvd3/issues/843, you can work around it by doing chart.growOnHover(false) which turns off the radius tween that messes it up.    

The others I'm not sure, but they sound like separate issues from the tooltip stuff we just fixed.  I'll close this issue and you can open new issues for each item that you can reproduce / get details on.   Cheers.

**Closed by liquidpele** 2015-03-17 01:25 UTC

**Comment by RenatoUtsch** [comment] 2015-03-17 01:50
Yes, that's it, thanks. The tooltips are working flawlessly now.

**Comment by RenatoUtsch** [comment] 2015-03-17 11:11
@liquidpele the tooltips stopped showing the information of some charts that are built correctly and used to have correct values on the tooltips. Now only NaN appears.

For example, in my repo in nvd3-scatter-chart/demo.json, the 2nd chart that does NOT set the size of the circles shows only NAN in the tooltips.
The first pie chart example also shows NAN but I don't know why, but it used to work correctly.
The 2nd discrete bar chart example also.

Maybe the tooltips are getting the wrong data?

**Comment by RenatoUtsch** [comment] 2015-03-17 13:19
@liquidpele also, if I create two charts, the tooltip of the second chart gets at the bottom of the page, in the wrong position.

This was a change done yesterday, because this wasn't happening.

**Comment by RenatoUtsch** [comment] 2015-03-17 13:22
Yeah, multiple charts on the page are now with all the tooltips except the tooltip of the first chart wrong. Will create a new issue.

**Comment by liquidpele** [comment] 2015-03-17 13:24
I didn't change anything yesterday that would affect tooltips:

https://github.com/novus/nvd3/commits/development

For the NaN thing, open a new issue and I'll take a look.

**Comment by RenatoUtsch** [comment] 2015-03-17 13:25
Lets close this here, look at #893.
