### ISSUE TITLE
multiBarChart top margin is forced to legend height

### ISSUE THREAD

**Issue by betelgeuse** [novus/nvd3#1045] opened 2015-05-20 11:49 UTC
https://github.com/nvd3-community/nvd3/blob/c41d501c1d1215844a8ae6b13646d15fc788c26b/src/models/multiBarChart.js#L192

I don't think the code should here be forcing the top margin to height of legend.

**Comment by liquidpele** [comment] 2015-05-20 19:08
Thanks for reporting, this is a duplicate of https://github.com/novus/nvd3/issues/515 though.  Cheers!

**Closed by liquidpele** 2015-05-20 19:08 UTC
