### ISSUE TITLE
More problems with Shadow DOM and tooltips

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#893] opened 2015-03-17 13:25 UTC
@liquidpele 

So, today I went and started to test the tooltips again, but a change yesterday must have broken something, because now if I create multiple charts only the tooltip of the first chart gets positioned right. All the other tooltips appear at wrong positions or at the bottom of the screen.

Also, I noticed another problem:
The tooltips stopped showing the information of some charts that are built correctly and used to have correct values on the tooltips. Now only NaN appears.

For example, in my repo in nvd3-scatter-chart/demo.json, the 2nd chart that does NOT set the size of the circles shows only NAN in the tooltips.
The first pie chart example also shows NAN but I don't know why, but it used to work correctly.
The 2nd discrete bar chart example also.

Maybe the tooltips are getting the wrong data?

**Comment by RenatoUtsch** [comment] 2015-03-17 13:26
I'll revert some nvd3 commits and see why the charts are being positioned incorrectly.

**Comment by liquidpele** [comment] 2015-03-17 13:32
whoops

**Comment by liquidpele** [comment] 2015-03-17 13:32
Okay, I won't be able to look at it for a while, so if you can track down the specifics in the meantime that woudl be helpful.

**Comment by RenatoUtsch** [comment] 2015-03-17 13:36
Actually, I reverted a lot of nvd3 commits and my own too in my repo to test, but the problem is always happening. So I assume it was a bug I didn't notice.

Later today I'll take a deeper look at this.

**Comment by RenatoUtsch** [comment] 2015-03-17 20:25
The Scatter Chart is also a bit strange, the tooltips are not moving correctly and they disappear if I stop on one of the points.

**Comment by liquidpele** [comment] 2015-03-17 20:29
this issue is closed now you will need to open something new and make sure to include specific reproduction steps or an online demo that I can look at

**Comment by liquidpele** [comment] 2015-03-17 20:30
oh wait this is the new one but I still need something more than a vague description

**Comment by RenatoUtsch** [comment] 2015-03-17 20:32
About the tooltip position problem, the width is being set correctly, but the height is not being changed.

I'll update the online demo for you.

**Comment by RenatoUtsch** [comment] 2015-03-17 20:41
- Scatter chart disappearance problem on the first chart, incorrect positioning and NaN values in the second chart.
http://renatoutsch.com.br/bower_components/polynvd3/nvd3-scatter-chart/demo.html

- Second pie chart with positioning problems and first chart with NaN values:
http://renatoutsch.com.br/bower_components/polynvd3/nvd3-pie-chart/demo.html

- Other charts:
http://renatoutsch.com.br/bower_components/polynvd3

A note worth mentioning is that the interactive guideline charts are working correctly, even with multiple charts.

**Comment by liquidpele** [comment] 2015-03-17 20:43
Cool!  Will look into this tonight...

**Comment by RenatoUtsch** [comment] 2015-03-17 20:52
Okay, I'll see what I can discover also...

**Comment by liquidpele** [comment] 2015-03-18 01:38
The scatter chart seems to mess up when it does a chart.update() ... works fine for me with pure nvd3 though... are you doing somethign to the data object passed or something? 

The pie chart showing NaN is a big bug, good catch!  I'm not using the x() and y() functions to propery get the x and y values in that chart.. probably others too... will have to fix that. 

The pie chart tooltip issue seems to be because it does extra magic calculations on the position when you specify chartContainer because it assumes that it's a position from interactive guideline... I'll probably have to add a "don't adjust position" option there... the one passed to the tooltip is actually correct if you put a breakpoint there.

**Comment by RenatoUtsch** [comment] 2015-03-18 01:43
Tomorrow I'll look at the scatter chart, but I don't remember doing anything to it. Yeah, I noticed now that it is a shadow dom only issue.

Thanks for the good work! I'll test everything once you fix the bugs and the tooltip position.

**Comment by RenatoUtsch** [comment] 2015-03-22 22:06
All the charts that I test, except for the discrete bar chart, are properly working now. The NaN values of all other charts were fixed.

Also, it seems the bug where the scatter chart tooltip disappears was fixed as well, maybe it was related to the getter and setter functions?

The only problem remaining is the tooltip positioning that gets wrong sometimes (and the discrete bar chart).

**Comment by liquidpele** [comment] 2015-03-23 02:37
You discrete bar chart works fine for me, what is the issue exactly?  

I'm looking at this:  http://renatoutsch.com.br/bower_components/polynvd3/nvd3-discrete-bar-chart/demo.html

**Comment by liquidpele** [comment] 2015-03-23 02:43
Just FYI, your scatter plot example still seems broken to me.  I'm using chrome. To reproduce:
1. resize the browser window
2. try to hover over some points, some points are ignored and others display the wrong data?
3. disable a single color (re-enable if you want)
4. Now it all works again

Something funky going on there... resizing the browser works fine in the nvd3 scatter example in our repo so it doesn't appear to be an nvd3 issue.

**Comment by liquidpele** [comment] 2015-03-23 12:59
ok I can't see any more issues can you test again and give me a demo of any further issues?

**Comment by RenatoUtsch** [comment] 2015-03-23 13:51
@liquidpele The scatter chart is indeed with problems when resizing. Maybe the points aren't getting recalculated after the resize because of some issue with the shadow dom.

Look at the second discrete bar chart example:
![screen shot 2015-03-23 at 10 49 43 am](https://cloud.githubusercontent.com/assets/836333/6781159/3c78e824-d14a-11e4-9575-66b565a488a4.png)

I remember that this example forced a bit the discrete bar chart because it had the data of a line chart, but nevertheless it used to work.

**Comment by RenatoUtsch** [comment] 2015-03-23 13:52
Oh, and the issue with the tooltip positioning is fixed now. Thanks.

When will a recompilation be done in the development branch? Because I have to download the repo instead of using bower and checking out development.

**Comment by liquidpele** [comment] 2015-03-24 02:10
@RenatoUtsch I think that should fix your discretebar chart, let me know.

**Comment by liquidpele** [comment] 2015-03-25 17:40
ping.  any further issues?

**Comment by RenatoUtsch** [comment] 2015-03-25 18:06
The scatter chart has the tooltips buggy when resizing, as you noticed. And this doesn't happen with any other charts. Need to dig deeper to know why.

One thing that would be interesting is adding a import.html file in nvd3's root that includes the nvd3.min.js script file, because I am kind of having conflicts. I'll make a pull request and explain it there.

**Comment by RenatoUtsch** [comment] 2015-03-25 18:06
I thought I commented that the discrete bar chart was fixed, thanks.

**Comment by liquidpele** [comment] 2015-03-25 20:02
cool, closing then.

**Closed by liquidpele** 2015-03-25 20:02 UTC
