### ISSUE TITLE
Support for logarithmic axes

### ISSUE THREAD

**Issue by jedbrown** [novus/nvd3#758] opened 2015-02-09 01:07 UTC
My current need is for scatterChart, but this seems better to do in a way that would work across all the chart types. I can work on this, but I'm new to nvd3 so would appreciate some guidance about implementation.

**Comment by robinfhu** [comment] 2015-02-09 01:12
Okay, so this may be kind of hard to implement, but maybe you can indeed work on this.  Obviously this resource will help: https://github.com/mbostock/d3/wiki/Quantitative-Scales

So  one idea may be to look at places where d3.scale.linear() is being used, and replace it with log()?  And you also have to worry about the axis.js file.  This is just a starting point.

**Comment by liquidpele** [comment] 2015-03-11 05:29
duplicate of https://github.com/novus/nvd3/issues/620

**Closed by liquidpele** 2015-03-11 05:29 UTC
Labels: Enhancement Request
