### ISSUE TITLE
MultiChart line z-index. 

### ISSUE THREAD

**Issue by renatoc** [novus/nvd3#339] opened 2013-11-05 15:40 UTC
With the multichart (bars and line) it is possible to bring the line to front? I  tried with z-index in css but I did not succeed.

**Comment by liquidpele** [comment] 2015-02-11 05:44
Duplicate of https://github.com/novus/nvd3/issues/293

**Closed by liquidpele** 2015-02-11 05:44 UTC

**Comment by leongaban** [comment] 2015-10-07 19:24
`Uncaught TypeError: d3.selectAll(...).moveToFront is not a function` Can this be reopened? This still seems to be a problem. http://stackoverflow.com/questions/33000725/how-to-position-nvd3-line-graph-above-all-other-area-bar-graphs | http://plnkr.co/edit/2pFDDITuPc7XaL0eR4AA?p=preview

**Comment by j2kenton** [comment] 2016-08-15 09:51
I successfully use:

        var groups = d3.selectAll(".nv-groups")[0][0];
        var series0 = d3.selectAll(".nv-series-0")[0][0];

        if (typeof groups != "undefined") {
          groups.appendChild(series0);
        }

This is based on @asarenski's answer above and [http://stackoverflow.com/questions/33000725/how-to-position-nvd3-line-graph-above-all-other-area-bar-graphs](url) and implement in angular-nvd3, in the  `$scope.options.chart.callback` property.
