### ISSUE TITLE
1.7.1 broke IE support for pie charts

### ISSUE THREAD

**Issue by VitalyTomilov** [novus/nvd3#763] opened 2015-02-09 13:40 UTC
I'm using 1.7.1, pie chart, and the chart appearance + hovering appear quite broken under IE 10-11. Changing back to version 1.2.0 solves the issue.

**Comment by liquidpele** [comment] 2015-02-09 13:50
The curse of IE continues...  I knew the hover was broken on IE10, but I can't reproduce any issues on IE11.  

For reference, I'm testing using this:  https://nvd3-community.github.io/nvd3/examples/donutChart.html

**Comment by liquidpele** [comment] 2015-02-09 13:52
Also I'm not sure how it worked in 1.2.0 since there was a really old bug report about the same thing...

**Comment by VitalyTomilov** [comment] 2015-02-09 14:24
My current usage path: D3 (3.5.4) -> NVD3 (1.2.0) -> Angular (1.3.13) -> Angular NVD3 (0.0.9)

It is easy to get lost where the issue arises. So far as I can see upgrading NVD3 to v1.7.1 breaks the pie chart when hovering over in IE11 for sure, while with 1.2.0 this doesn't happen.

That example you use relies on v.1.7.0 that never existed, as far as the GitHub versioning goes.

**Comment by liquidpele** [comment] 2015-02-09 15:35
Well, for starters try the latest nvd3 version 1.7.1 which was brought over from nvd3-community... it has a lot of rewrite so any issues should be tested against that first.  However, I did reproduce issues with IE10 at least, so at some level this is a bug and we'll try to look at it :)

If you can give us a jsfiddle that shows the IE11 issue (without angular, just nvd3 please) using the latest nvd3 code then it would get a higher priority.

**Comment by robinfhu** [comment] 2015-02-11 01:10
I'm on IE-11, and aside from https://github.com/novus/nvd3/issues/771 which is everywhere, the chart looks and feels okay.

**Comment by petersondrew** [comment] 2015-02-11 14:21
@robinfhu Same as #771, I'm not seeing the issue in my development branch on IE11. Something is up.

**Comment by liquidpele** [comment] 2015-02-17 03:28
Closing this until something reproducible is provided.

**Closed by liquidpele** 2015-02-17 03:28 UTC
Labels: Bug
