### ISSUE TITLE
Removing legend doesnot clear its area

### ISSUE THREAD

**Issue by isadaqah** [novus/nvd3#465] opened 2014-03-05 20:47 UTC
Specifying `.showLegend(false)` does remove the legend, but doesnot clear the space taken by the legend completely. I would like the donut to take the full svg area.

**Comment by liquidpele** [comment] 2015-02-11 22:50
duplicate of  https://github.com/novus/nvd3/issues/693

**Closed by liquidpele** 2015-02-11 22:50 UTC
Labels: Fix
