### ISSUE TITLE
Support v4+ of d3?

### ISSUE THREAD

**Issue by andrewstoker** [novus/nvd3#1812] opened 2016-09-14 12:24 UTC
Are there any plans for nvd3 to support version 4 of d3?

**Comment by ehartford** [comment] 2016-09-18 11:51
Duplicate of https://github.com/novus/nvd3/issues/1681

**Comment by liquidpele** [comment] 2016-09-18 13:20
nvd3 is almost entirely community driven at this point, so anyone who would like v4 support please send us a pull request :)

**Closed** 2016-09-18 13:20 UTC

**Comment by bgth** [comment] 2017-09-09 08:58
Can you please check #2082 and see if anyone can spare some time on the migration to v4? Thanks in advance..
