### ISSUE TITLE
Stacked Area Chart 'expanded' highlights not updated on data change or series toggling

### ISSUE THREAD

**Issue by PeterVermont** [novus/nvd3#1814] opened 2016-09-15 17:59 UTC
If I change the data for the chart when in expanded mode the highlighted points will still be for the initial data. The text percentages are correct though. I believe that 'point.display.y' in stackedAreaChart.js line 422 is not being updated.

Here is the initial data:
![image](https://cloud.githubusercontent.com/assets/889233/18560960/d45272f8-7b4b-11e6-9b9f-2eee31d157b0.png)

And here it is after changing the data:

![image](https://cloud.githubusercontent.com/assets/889233/18561028/18e05dc2-7b4c-11e6-880e-e432e39284d1.png)

**Comment by PeterVermont** [comment] 2016-09-15 18:25
The bug is even easier to see by just removing one of the data groups by single clicking in the legend. In the picture below I have clicked (removed) the data for the largest category Home:

![image](https://cloud.githubusercontent.com/assets/889233/18562027/262b4830-7b50-11e6-85f3-177707ceb415.png)

**Comment by PeterVermont** [comment] 2016-09-16 14:43
Replicated the bug in the Nvd3 examples:

![image](https://cloud.githubusercontent.com/assets/889233/18589717/fd5e4eca-7bf9-11e6-89bf-784a3296b855.png)

When I toogle off the large series'Information Technology you can see that the highlights are still showing the previous locations:

![image](https://cloud.githubusercontent.com/assets/889233/18589792/4cd9be58-7bfa-11e6-94d3-516bda75fe0f.png)

**Comment by PeterVermont** [comment] 2016-09-16 14:44
Note: if you switch to either Stream or Stacked and then back to expanded the highlighted points are updated to the correct locations

**Comment by liquidpele** [comment] 2016-09-16 15:33
Hmm, this might be related to https://github.com/novus/nvd3/issues/1777 too

**Comment by PeterVermont** [comment] 2016-09-16 16:14
Additional info: the data object is correctly updating the display info but some of the display objects being retrieved are stale/old objects

I added some logging and stored a date into the display object when the display was set and then logged these values when the highlight was drawn. Note that is the last series point it is using an old display value:


nv.d3.js:13297 DISPLAY SET first series 12 noon: 1 creationTime: 11:59:55
nv.d3.js:13298 DISPLAY SET last series 12 noon: 1 creationTime: 11:59:55

nv.d3.js:13929 HIGHLIGHT first series 12 noon: 1 creationTime: 11:59:55
nv.d3.js:13930 HIGHLIGHT last series 12 noon: 0.39852557405754746 creationTime: **_# 11:59:32_**

**Comment by PeterVermont** [comment] 2016-09-16 16:21
It looks like the highlight is not using the latest filtered data -- in the example it is not obvious but the DISPLAY SET first and last point are the SAME point because data only had one series. In the display Data was still size two (from before the second to last series being toggled off). I will make a new example...

**Comment by PeterVermont** [comment] 2016-09-16 18:33
#### Found the problem!

Point positions are not being updated because the data ids are unchanged and therefore the enter selection code does not get run even though the position needs to be updated.

The issue is that 'expanded' points are odd in that their attributes such as position can change even though their id does not.

Potential fixes (although I am not great at d3): 

1. - Include the y-position of the point as part of each points data key. 
2. -Alternatively, move the translation into the update selection rather than the enter selection.

For now, since I did not want to edit my nvd3 so I work around the bug by removing the points when I get a click in the legend which will cause the points to be in the enter selection and terefore have their position updated.

```
chart.legend.dispatch.on('legendClick', function (e) {
 d3.select(chart.container).selectAll('path.nv-point').remove();
});

```

Relevant code is in scatter.js starting at line 427:
```
            points.enter().append('path')
                .attr('class', function (d) {
                    return 'nv-point nv-point-' + d[1];
                })
                .style('fill', function (d) { return d.color })
                .style('stroke', function (d) { return d.color })
                .attr('transform', function(d) {
                    return 'translate(' + nv.utils.NaNtoZero(x0(getX(d[0],d[1]))) + ',' + nv.utils.NaNtoZero(y0(getY(d[0],d[1]))) + ')'
                })
                .attr('d',
                    nv.utils.symbol()
                    .type(function(d) { return getShape(d[0]); })
                    .size(function(d) { return z(getSize(d[0],d[1])) })
            );
            points.exit().remove();

```

**Comment by ThomasBrierley** [comment] 2016-09-17 04:45
This was also a regression caused by my optimisation but with a separate pruning dependency to #1777

The issue was not the IDs changing. The getCache function can handle the series changing IDs because it uses the series ID as the key to the cache object. Instead it seems that the stacked area chart uses numerical keys instead of x, y for position as most models do.

If anyone is aware of any other alternative point position keys or other unusual models where point position is affected by other keys it would be good to know. Currently point update pruning is determined by chart dimensions and point x, y, 0, 1 values.

**Comment by PeterVermont** [comment] 2016-09-19 15:46
I did not say the data ids were changing. In fact it is that the data ids remained the same but the positions changed. With the data ids not changed the code in the enter selection is not re-run.

If the code for the translation was in the update selection (which automatically always includes the enter selection) the positions would correctly be changed.

Unfortunately, if in the update selection, the translations would be applied all the time for all chart types.

I don't know the code but the essential issues seems to be that expanded positions are done differently than stream or stacked. While all three make the data series positions dependent on each other stacked and stream actually change the data point locations whereas expanded does on-the fly recalculation.

**Comment by ThomasBrierley** [comment] 2016-09-20 17:33
Hi @PeterVermont Sorry I must have miss understood what you meant. Thank's for the bug report, which along with input from @liquidpele outlined an important flaw in an optimisation I made to this code. It's all fixed now on this PR: #1777 I hope I didn't cause you too much pain.

This was a regression so if you need the fix soon you could use a version older than v1.8.4 or wait for the next patch which I believe should be soon.

> If the code for the translation was in the update selection (which automatically always includes the enter selection) the positions would correctly be changed.
> 
> Unfortunately, if in the update selection, the translations would be applied all the time for all chart types.

Although the behaviour might suggest otherwise, the translation code is an was in the update selection. Before the disadvantage that you outline was apparent with large dynamically updated data-sets being not being interactively usable.

The "getDiffs" filter in the update selections is culling the unchanged points which allows the update to be substantially faster, the bug was caused by the getDiffs function using a potentially different method to get point attributes for charts that override the default. (details in the PR).

**Comment by PeterVermont** [comment] 2016-09-20 19:10
Hi @ThomasBrierley,

I see you are correct that there is a translation applied to the update selection. I was fooled because the translation is ALSO applied on the enter() (without the diffs filter) so I did not look down further.

Thanks for taking the time to explain what was going on.

There are a couple small optimizations I can see:
•	It is not necessary for the translation and the symbol code to be both in the enter and the update since the enter selection is appended to the update selection. This will work because getDiffs will not find the cache entry for new points and therefore they will pass the filter.
•	The data filter using scaleDiffs is unnecessary since it includes all points.

Below is my version of the section of relevant code in case it is helpful to you:
```
points.enter().append('path').attr('class', function (d) {
		return 'nv-point nv-point-' + d[1];
	}).style('fill', function (d) {
		return d.color
	}).style('stroke', function (d) {
		return d.color
	})
	//                .attr('transform', function(d) {
	//                    return 'translate(' + nv.utils.NaNtoZero(x0(getX(d[0],d[1]))) + ',' + nv.utils.NaNtoZero(y0(getY(d[0],d[1]))) + ')'
	//                })
	//                .attr('d',
	//                    nv.utils.symbol()
	//                    .type(function(d) { return getShape(d[0]); })
	//                    .size(function(d) { return z(getSize(d[0],d[1])) })
	//            )
;
points.exit().remove();
groups.exit().selectAll('path.nv-point').watchTransition(renderWatch, 'scatter exit').attr('transform', function (d) {
	return 'translate(' + nv.utils.NaNtoZero(x(getX(d[0], d[1]))) + ',' + nv.utils.NaNtoZero(y(getY(d[0], d[1]))) + ')'
}).remove();

var filteredPoints = scaleDiff ? points : points.filter(function (d) {
	return getDiffs(d, 'x', 'y');
});

filteredPoints.watchTransition(renderWatch, 'scatter points').attr('transform', function (d) {
	//nv.log(d, getX(d[0],d[1]), x(getX(d[0],d[1])));
	return 'translate(' + nv.utils.NaNtoZero(x(getX(d[0], d[1]))) + ',' + nv.utils.NaNtoZero(y(getY(d[0], d[1]))) + ')'
});

filteredPoints = scaleDiff ? points : points.filter(function (d) {
	return getDiffs(d, 'shape', 'size');
});

filteredPoints.watchTransition(renderWatch, 'scatter points').attr('d', nv.utils.symbol().type(function (d) {
	return getShape(d[0]);
}).size(function (d) {
	return z(getSize(d[0], d[1]))
}));

```

**Comment by ThomasBrierley** [comment] 2016-09-21 01:34
Great! removal of the duplicate translation and symbol code should make a nice speedup because it's doubling the DOM access for new points :) it's also just not good to have literally duplicate code anyway.

I think moving the filter would have less effect unfortunately. When scaleDiff or sizeDiff is true then getDiffs doesn't get called anyway due to the order, but there is still the encapsulating anonymous function so In theory it should save n x function calls... Although in reality i'm pretty sure that will not happen due to JavaScript optimising compilers (easy to determine that scaleDiff is not changing and is true for all).

More to the point though is that if scaleDiff or sizeDiff are true then it's kinda game over because the DOM node access outweighs all other processing in JavaScript, that's basically all that the point culling is trying to avoid, it actually adds some overhead, extra point function calls and lookups for all points.

Beyond abandoning stateful DOM based graphing I think this could be avoided if the points were set in axis based coordinate space, that way changes to chart and axis size would naturally rescale that coordinate space without having to access each point node... but there are issues with that approach too and it's beyond the scope of nvd3 really, I was just going after low hanging fruit :D

**Comment by ThomasBrierley** [comment] 2016-09-21 11:13
@PeterVermont Do you want me to add your changes into my PR or are you going to do another PR?

**Comment by PeterVermont** [comment] 2016-09-21 20:27
Please make whatever changes you think make sense. I have never done a PR on public projects!

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Closed** 2016-09-26 15:41 UTC

**Comment by liquidpele** [comment] 2016-09-26 15:44
https://github.com/novus/nvd3/pull/1817 might have fixed, can someone verify lastest master?

**Comment by PeterVermont** [comment] 2016-09-26 15:54
I can no longer replicate the issue I saw at: http://nvd3.org/examples/stackedArea.html

Nice job!
