### ISSUE TITLE
scatterPlusLineChart legend cut off issue

### ISSUE THREAD

**Issue by olemi** [novus/nvd3#322] opened 2013-10-22 07:06 UTC
In a scatterPlusLineChart the legend is cut off.
I gets visible when a window resize event occurs, or when hte user click on one of the visible legend items.

The issue is reproducible with the ScatterChartTest.

![legend](https://f.cloud.github.com/assets/3709642/1379232/6d0a83ca-3ae8-11e3-9ca6-495ac2281ab6.png)

**Comment by robinfhu** [comment] 2015-02-12 03:58
Oh this is a dupe of: https://github.com/novus/nvd3/issues/777

Closing this ticket.

**Closed by robinfhu** 2015-02-12 03:58 UTC
