### ISSUE TITLE
d3.time.scale compatibility

### ISSUE THREAD

**Issue by ninjudd** [novus/nvd3#145] opened 2013-05-30 00:42 UTC
It seems to me that `d3.time.scale` cannot be used with nvd3.

For example, this seems like it should work to me, but it doesn't:

```
chart.xAxis.scale(d3.time.scale());
```
It seems to ignore the tickFormat (add possibly the tickValues) completely.

The reason I want to use `d3.time.scale` is because it seems to have good handling of automatic time ticks (https://github.com/mbostock/d3/wiki/Time-Scales#wiki-ticks). Specifically, it looks like it automatically aligns tick marks to human friendly intervals:

```
1-, 5-, 15- and 30-second.
1-, 5-, 15- and 30-minute.
1-, 3-, 6- and 12-hour.
1- and 2-day.
1-week.
1- and 3-month.
1-year.
```

Is there any way to get nvd3 working with d3 time scales? Is there something I'm missing? I'm happy to help out if someone can point me in the right direction.

**Comment by heliodor** [comment] 2015-03-03 17:19
I posted a pretty complete time series example on JsFiddle: http://jsfiddle.net/3r88bgjw/ Hope it helps.

It shows how to: 1) set the x scale to a time scale so default ticks are round values, 2) format the tooltip, 3) put tick marks on the x axis for usability, 4) use bars instead of line so any gaps are visible, 5) use multi-format so that time labels are short and fit nicely.

**Comment by AlonAmsalem** [comment] 2015-03-05 19:12
amazing, thanks!

**Comment by mb-dev** [comment] 2015-03-06 01:21
Thanks!

**Comment by liquidpele** [comment] 2015-03-06 01:38
@robinfhu Short term we should add that jsfiddle code as an example since it shows off a lot... long term we should probably merge in the main changes to historicalBar.  Time series makes a lot of sense for that chart, and line chart too.

**Comment by liquidpele** [comment] 2015-03-09 16:00
The jsfiddle example was merged into the project so there is an example there to work from at least, and w'ell try to make using a time series easier using that as a starting point.  Closing this story, and if anyone wants to help out send us a pull request :)

**Closed by liquidpele** 2015-03-09 16:00 UTC
Labels: Feature

**Comment by milimetric** [comment] 2015-03-20 23:22
The bar timeseries chart was not too useful in my case, but adapting code from the other responses I was able to make the lineWithFocusChart work well:

        chart.lines.xScale(d3.time.scale());
        chart.lines2.xScale(d3.time.scale());

        var timeFormat = d3.time.format('%Y-%m-%d');
        chart.xAxis.tickFormat(timeFormat);
        chart.x2Axis.tickFormat(timeFormat);

That's the only code you need in addition to the example from http://nvd3-community.github.io/nvd3/examples/lineWithFocusChart.html

**Comment by dlu306090** [comment] 2015-04-06 23:11
Does this handle automatic time ticks though? I can't seem to get those to work, because 
 var timeFormat = d3.time.format('%Y-%m-%d');
only makes all the dates a specific format. But I want to vary the format based on the length of time selected in the brush area, i.e. if less than a day interval is selected, I want the format in time(hh:mm:ss) rather than dates(mm/dd/yy).

**Comment by heliodor** [comment] 2015-04-06 23:16
dlu306090, you can do that with the jsfiddle I posted earlier. Look at the 'tickMultiFormat' variable to see how it's done. You can see it in action better here: https://jsfiddle.net/kaLt5aqr/

**Comment by dlu306090** [comment] 2015-04-06 23:19
Hmm..I don't really understand how "resizing the panel to see the various types of time labels" works. What do you mean by resizing the panel? When I do it the chart doesn't itself resize. I just can't see half of it.

**Comment by jufemaiz** [comment] 2015-04-07 03:36
@dlu306090 you'll need to hit "run" again after resizing as the jsfiddle instance hasn't bound resize events to rerender.

**Comment by dlu306090** [comment] 2015-04-07 04:50
Ah, it works. Fantastic, thanks so much! So I think I've finally got the hang of this weird d3 date axis thing. I suppose this wasn't really what I was looking for though. I have an array of dates and values, and these values are being collected at very specific times, such as 03/24/15 03:34:01pm. I know that with tickMultiFormat you can get d3 to format starts of hours, starts of days, etc, certain ways, but what if I just want to base my formats on how large the range of days selected in the lineWithFocusChart is? Because currently, since all my data is so precise, everything is just defaulting to the rule "seconds" format. I'd like to be able to see when I zoom out just month names maybe, and then when I zoom in, to see days and hours, even though none of my dates (the x-values) are exactly the beginning of a month or a year. Is this functionality possible with d3?

**Comment by heliodor** [comment] 2015-04-07 14:35
The way to do that is to:
1) Create a time scale as a variable.
2) Pass that scale to the axis.
3) Call tickFormat() with your own formatting function.
4) In that formatting function, get the current time span using scale.domain() and return whatever label you deem appropriate based on that time span.

**Comment by Serveurperso** [comment] 2015-05-05 00:13
One day lost just for 2 undocumented strange behavior to get a readable time axis....
````
        chart.lines.xScale(d3.time.scale());
        var timeFormat = d3.time.format('%H:%M:%S');
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(timeFormat)
        ;
````

**Comment by joshjordan** [comment] 2015-05-05 01:20
We would welcome a pull request to improve documentation.

**Comment by Serveurperso** [comment] 2015-05-05 06:44
Hello,  I can't document this because there is a regression/bug, it disable the bubble pop-up with values

**Comment by Serveurperso** [comment] 2015-05-05 12:13
I solved my problem, now I can make a cool sample for documentation...
Tooltip is now OK and xScale is nice:)

````
        chart.lines.xScale(d3.time.scale());
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(function(d) {
                return d3.time.format('%H:%M:%S')(new Date(d))
            });
        ;
````
