### ISSUE TITLE
Orientation support in legends

### ISSUE THREAD

**Issue by gardenermike** [novus/nvd3#318] opened 2013-10-17 15:42 UTC
I have implemented orientation support in legends, and would like feedback as to how this would best be appreciated by the project maintainers.  See https://github.com/radiatemedia/nvd3/commit/4db520a1410d30b7d2412e43347a88b56e5a577c to see the working code.  Ideally, I'd like to see the legend positioning code extracted into a function in the legend model, then shared by all charts equally.  This would make for much more straightforward enhancements and fixes to legend positioning in the future.  Would this effort be considered appropriate?  If so, my team will work on it and submit a pull request.

Thank you!

**Comment by liquidpele** [comment] 2015-02-11 05:50
duplicate of https://github.com/novus/nvd3/issues/189

**Closed by liquidpele** 2015-02-11 05:50 UTC
