### ISSUE TITLE
tooltips aren't positioned correctly inside scrollable div

### ISSUE THREAD

**Issue by anthonyettinger** [novus/nvd3#815] opened 2015-02-24 20:39 UTC
When I put more than one chart inside a scrollable div, the tooltips aren't positioned correctly once I scroll the div down a bit.

It appears the tooltip positioning is calculated to the window. Is there anyway to make it relative to a parent element like `.chart-container` instead of the window?

**Comment by liquidpele** [comment] 2015-02-24 20:41
Closing as duplicate of https://github.com/novus/nvd3/issues/809

**Closed by liquidpele** 2015-02-24 20:41 UTC
