### ISSUE TITLE
Tooltip position is not correct with two columns of chart containers in a page.

### ISSUE THREAD

**Issue by ijab** [novus/nvd3#238] opened 2013-08-26 18:13 UTC
By default, nvd3 would create tooltip's container <div> within the chart <svg>'s parent element(maybe a <div>). Reproduce the bug:
1) Put two divs there and the first one with style float:left;

    <div style="float:left"><p>text</p><p>text</p><p>text</p><p>text</p></div>
    <div id="chart_container"></div>

    create a MultiBarChart into "chart_container" div, the tooltip's position would be much higher.

2) Create a table with two columns and put the chart in the second column, and then create a MultiBarChart into the second column. The tooltip's position would be totally wrong, in the first column.

     <table>
       <tr>
         <td><div>many content here</div></td>
        <td><div id="chart_container"></div></td>
       </tr>
     </table>

Two possible solutions to this problem:
a) Make the chart's container position:relative and the get the tooltip's position by d3.mouse(chart's container). This solutions depends on the end users.

b)My suggestion is to create the tooltip in the body, not in the chart container, getting the tooltip position by d3.mouse('body'), and that's the general way. 

iJab

**Comment by liquidpele** [comment] 2015-02-11 04:13
duplicate of more recent tooltip issues.

**Closed by liquidpele** 2015-02-11 04:13 UTC

**Comment by cserpell** [comment] 2015-04-23 14:21
Duplicate of which one?

**Comment by liquidpele** [comment] 2015-04-23 14:28
Tooltips were completely refactored in the development branch (and v1.8.1-alpha) so older tooltip issues *should* be fixed... or at least would require new issues to be opened for new problems :)

**Comment by cserpell** [comment] 2015-04-23 14:33
Thanks, sorry about asking to early. Already read that the API was completely changed in 1.8.0. I will wait next release goes through angular-nvd3, as I am using that libraryto include them into angularjs.
