### ISSUE TITLE
lineWithFocusChart's brushExtent option doesn't properly fade out the right side

### ISSUE THREAD

**Issue by lukaprelic** [novus/nvd3#855] opened 2015-03-09 00:02 UTC
There is an error when drawing a linewithfocuschart where the right background (white shading) doesn't appear when rendering a graph with a preset focus range.
The right white shading width is wrongly calculated and therefore, doesn't display when the graph is rendered. Look at the first picture.

The problem is in updateBrushBG() function where the graph width is calculated using
rightWidth = x.range()[1] - x2(d[1]);. x.range()[1]. x.range()[1]  returns 1 even though it should be the graph width e.g. 600px. Its because it calculates it while the graph is not drawn yet.

fix is using availableWidth:
rightWidth = availableWidth - x2(d[1]);

Before Fix:
![without fix](https://cloud.githubusercontent.com/assets/4257996/6548297/be5e143c-c5eb-11e4-9e6e-6f2bd39334fa.jpg)

After Fix:
![with fix](https://cloud.githubusercontent.com/assets/4257996/6548299/c5f9ff30-c5eb-11e4-9632-c3ece5516ac7.jpg)

Dont have pull request but easy implement by someone else who has access.

**Comment by liquidpele** [comment] 2015-03-09 13:45
I can't reproduce this issue, be sure you're using the latest development branch and can you provide a jsfiddle or detailed steps?   I'm reluctant to just make this change since the leftWidth uses x.range()[0] which would also return a technically wrong value if x.range()[1] was.

**Comment by lukaprelic** [comment] 2015-03-09 16:05
http://jsfiddle.net/lifebennder/p6na5y6n/8/ Here you go.

**Comment by liquidpele** [comment] 2015-03-09 16:11
Your link doesn't work, you can't hotlink javascript from github, use https://rawgit.com/

**Comment by liquidpele** [comment] 2015-03-09 16:12
Also you have d3 3.0.4 loading, but our min required is 3.4.4

**Comment by lukaprelic** [comment] 2015-03-09 16:21
http://jsfiddle.net/lifebennder/p6na5y6n/9/ here you go.

**Comment by liquidpele** [comment] 2015-03-10 01:31
Chrome doesn't let you load javascript from github directly.   I took the liberty of fixing your jsfiddle for you:    http://jsfiddle.net/p6na5y6n/12/

Confirmed bug.

**Comment by liquidpele** [comment] 2015-03-17 02:43
Created https://github.com/novus/nvd3/pull/891, closing this issue.

**Closed by liquidpele** 2015-03-17 02:43 UTC
Labels: Bug
