### ISSUE TITLE
Seeing "NaN" sometimes in interactive guides on stacked area charts

### ISSUE THREAD

**Issue by portante** [novus/nvd3#1081] opened 2015-06-17 21:45 UTC
Hello, it appears that sometimes our graphs for StackedAreaCharts get NaNs in the interactive guides.

See attached image.

![nan in interactive guide lines](https://cloud.githubusercontent.com/assets/949097/8219448/2aacd102-1518-11e5-8c30-a089424eedf9.png)

We are using the following x-axis formatting:

    var customTimeFormat = d3.time.format.multi([
      [".%L", function(d) { return d.getMilliseconds(); }],
      [":%S", function(d) { return d.getSeconds(); }],
      ["%I:%M", function(d) { return d.getMinutes(); }],
      ["%I %p", function(d) { return d.getHours(); }],
      ["%a %d", function(d) { return d.getDay() && d.getDate() != 1; }],
      ["%b %d", function(d) { return d.getDate() != 1; }],
      ["%B", function(d) { return d.getMonth(); }],
      ["%Y", function() { return true; }]
    ]);
    var xTickFormat = function(d) { return customTimeFormat(new Date(d)); };

**Comment by liquidpele** [comment] 2015-06-17 22:05
Nice...probably due to it using a linear scale instead of d3.time.scale() ?

**Comment by portante** [comment] 2015-06-18 00:17
We do:

    nv.addGraph(function() {
      thischart = nv.models[graph_type]()
          .xScale(d3.time.scale.utc())
          .x(xAccessor)
          .y(yAccessor)
          .useInteractiveGuideline(true)
          .color(keyColor);

Where `graph_type` is a choice between `lineChart` and `stackedArea`.  It seems to only happen with `stackedArea`.

**Comment by mcorstjens** [comment] 2015-07-13 14:29
I've also encountered this bug. Found a workaround by rebuilding the HTML within the tooltip by using `.interactiveLayer.tooltip.contentGenerator`:

```javascript
chart.interactiveLayer.tooltip.contentGenerator(function (d) {
	var header = d.value;
	var headerhtml = "<thead><tr><td colspan='3'><strong class='x-value'>"+header+"</strong></td></tr></thead>";
				
	var bodyhtml = "<tbody>";
	var series = d.series;
	series.forEach(function (d) {
		bodyhtml = bodyhtml+"<tr><td class='legend-color-guide'><div style='background-color: "+d.color+";'></div></td><td class='key'>"+d.key+"</td><td class='value'>"+d.value+"</td></tr>";
	});
	bodyhtml = bodyhtml+"</tbody>";
	return "<table>"+headerhtml+''+bodyhtml+"</table>";
});
```

**Comment by spiermar** [comment] 2015-07-14 00:16
+1

Same issue. Easy to reproduce with examples. Just change %x for %X on:

http://nvd3-community.github.io/nvd3/examples/stackedAreaChart.html

**Comment by jgrund** [comment] 2015-07-16 14:25
It's because `interactiveLayer.tooltip.headerFormatter` tries to reprocess an already processed x axis value. It can be fixed by overriding that formatter with an identity function, i.e:

```
 chart.interactiveLayer.tooltip
                .headerFormatter(fp.identity);
```

**Comment by richardlawley** [comment] 2015-07-29 15:48
I suspect headerFormatter _should_ be being passed the unformatted value, so that the same formatting functions that are used on an axis can be used in the header.

**Comment by yongcho822** [comment] 2015-08-16 06:00
![screen shot 2015-08-16 at 1 57 59 am](https://cloud.githubusercontent.com/assets/11731033/9292221/430b0cfc-43ba-11e5-8b5a-0dc47b3bd75a.png)

In my stacked area chart, I'm getting a similar bug - could any of the pros (everyone who commented) help out a noob by telling me where exactly I need to implement some changes - whether it's in my HTML, nv.d3.js, or nv.d3.css?

I've solved the y-axis date issue with this:
        chart.xAxis.tickFormat(function(d) { return d3.time.format('%I:%M %p')(new Date(d)) });

**Comment by yongcho822** [comment] 2015-08-16 06:39
^Solved:

   ``` interactiveLayer.tooltip
        .headerFormatter(function(d, i) {
            return nv.models.axis().tickFormat()(d, i);
        })```

Replace xAxis with nv.models.axis() to update after reformatting the xAxis.

**Comment by Cybermaxs** [comment] 2015-09-29 08:53
any update on this ?

**Comment by websiteduck** [comment] 2015-10-16 19:29
In my case I want to show the date on the X axis and the date+time in the tooltip.
```
chart.xAxis.tickFormat(function(d) { 
        return d3.time.format('%x')(new Date(d));
});
chart.interactiveLayer.tooltip.headerFormatter(function (d) {
        return d3.time.format('%x %-I %p')(new Date(d));
});
```

This does not work because `d` in the second function is the already processed value from the first function.  

My current workaround is to include the time on the X axis and then just return `d` as-is in the second function but that's not ideal.
```
chart.xAxis.tickFormat(function(d) { 
        return d3.time.format('%x %-I %p')(new Date(d));
});
chart.interactiveLayer.tooltip.headerFormatter(function (d) {
        return d;    
});
```

**Closed** 2015-10-19 13:33 UTC
Labels: Bug

**Comment by douglasg14b** [comment] 2017-03-06 23:27
Same issue exists on the linePlusBarChart

**Comment by sean-macfarlane** [comment] 2017-06-20 02:14
The  issue is that it is passing the values to tickFormat as type String for the Tooltips. 
If you add:
```
if (typeof d === 'string') {
     d = parseFloat(d);
}
```
To tickFormat it will make sure the parameter of new Date() is a numeric value and prevents it from returning NaN.

Full Solution
```
chart.xAxis.tickFormat(function(d) { 
                    if (typeof d === 'string') {
                        d = parseFloat(d);
                    }
                    return d3.time.format('%m/%d/%y')(new Date(d));;
                });
```

**Comment by khuramshahzad** [comment] 2017-10-05 08:48
In my case i am using 
` if (typeof d === 'string')
                        {
                            d = parseFloat(d);
                        }
                        return d3.time.format('%H : %M')(new Date(d))`

**Comment by aganesan** [comment] 2019-03-13 09:45
in my case i am using return d if d is string
if (typeof d === 'string') { 
      return d;;
 }
