### ISSUE TITLE
Linechart - IE11 tooltip jumps off base when useInteractiveGuideline = true

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#806] opened 2015-02-18 22:45 UTC
When useInteractiveGuideline is on and using IE11 the tooltip jumps way to the top left of the chart if the cursor hovers directly over a dot on a line.  

Thoughts?

**Comment by robinfhu** [comment] 2015-02-18 22:46
Can we see a screenshot of this?  I think this may be pointer-events:none issue...

**Comment by mpGitHub** [comment] 2015-02-18 23:27
It wasn't letting me upload a pict.  Basically hover slowly over a line such as "Random Points" in the default example.  The tooltip flickers on and off like it's losing focus.  Then out of the blue it displays in the top left of the chart.  The dots on the far left of the chart are focused on even though the mouse is still in the center of the chart.

**Comment by liquidpele** [comment] 2015-02-19 00:17
Just FYI, for pictures you can just upload to imgur.com and either link to it here or embed it in the comment like the markdown example for images shows:   https://guides.github.com/features/mastering-markdown/

**Comment by mpGitHub** [comment] 2015-02-19 15:34
![tooltip](https://cloud.githubusercontent.com/assets/8506767/6269678/76811706-b81a-11e4-949a-c692405373ae.png)

**Comment by mpGitHub** [comment] 2015-02-19 15:35
Ha - I tried to upload the pict w/ Firefox and IE, but it only worked in Chrome.

**Comment by mpGitHub** [comment] 2015-02-19 15:38
The useInteractiveGuideline in Chrome is a smooth displaying tooltip that doesn't flicker on and off and jump around like in the pict above.  Seems like in IE it keeps losing context of where it is.  It would make sense that it could be a pointer-events issue.

**Comment by liquidpele** [comment] 2015-02-19 15:39
That's not the latest code, which has an added pink line.    

Grab latest from the development branch, build it via https://github.com/novus/nvd3#building-latest

Then open the index.html file there and you should see the examples page locally, see if still happens.    I can't reproduce this though...

**Comment by liquidpele** [comment] 2015-02-19 15:40
Oh wait, IE11, that's right, let me try to find a windows vm...

**Comment by robinfhu** [comment] 2015-02-19 15:40
Okay, from now on, we need to start developing all new features in IE11.

**Comment by liquidpele** [comment] 2015-02-19 15:42
ew

**Comment by mpGitHub** [comment] 2015-02-19 15:42
I just did a repro with IE11 in the latest branch.

Y - IE11 stinks, but it's still used a bunch.

**Comment by mpGitHub** [comment] 2015-02-19 15:45
Where I am I need things to play nice in IE10+.  

I turned off useInteractive because of this issue as most users here are forced to use IE unfortunately.  I'd like to turn it on though as it is cool functionality.

**Comment by liquidpele** [comment] 2015-03-09 15:44
This should hopefully be fixed by PR https://github.com/novus/nvd3/pull/851

**Comment by liquidpele** [comment] 2015-03-10 14:07
PR is merged, this should be fixed now, closing.  Please create any issues you find with the new tooltip code!

**Closed by liquidpele** 2015-03-10 14:07 UTC
