### ISSUE TITLE
Tooltip Location

### ISSUE THREAD

**Issue by DefunctExodus** [novus/nvd3#361] opened 2013-11-22 21:09 UTC
Good Afternoon,

I am having some issues with the the tool tip placement on my chart, I currently have a row of pie charts with a line chart below it.

The tool tip from the line chart wants to attach to the svg elements (or so it appears)  from the pie charts.

This issue only happens if the line chart is below the pie charts.  I can not seem to find out why this is happening any suggestions would be helpful.

**Comment by liquidpele** [comment] 2015-02-11 00:47
Duplicate of https://github.com/novus/nvd3/issues/189

**Closed by liquidpele** 2015-02-11 00:47 UTC
